### ISSUE TITLE
`*Systems.wait()` spins as fast as possible while the system is paused

### ISSUE THREAD

**Issue by ImVexed** [mlange-42/arche#304]
Hello!

First off, thanks for making this great library!

I've observed 100% cpu usage from the goroutine handling the `*Systems.Run()` even while the system is paused. I looked into it a bit, and it seems like while the system is paused `s.nextUpdate` is not set to anything. Such that the sleep in `*Systems.wait()`:
```go
	t := time.Now()
	wait := nextUpdate.Sub(t)

	if wait > 0 {
		time.Sleep(wait)
	}
```

Is always negative and causes the wait to return immediately. I'm trying to use this as a runtime for a game server, so Ideally, I can run as many systems in parallel as possible. Which makes this functionality less than ideal as I'm spending an entire core on per system even if it only is using a fraction of the core normally.

**Comment by ImVexed** [comment]
For what it's worth, I took a quick swing at using `ticker` instead of the way it's currently handled with time offsets and it's worked well for me, and reduced paused/unpaused process usage down to 30ms of system time, vs the previous 29seconds over the 30 second measurement:
```go
// Run the model.
func (s *Systems) run() {
	if !s.initialized {
		s.initialize()
	}

	// Create a ticker for the game logic updates
	ticker := time.NewTicker(time.Duration(time.Second / time.Duration(s.TPS)))

	// Create a ticker for UI updates
	uiTicker := time.NewTicker(time.Duration(time.Second / time.Duration(s.FPS)))

	terminate := s.termRes.Get()

	for !terminate.Terminate {
		select {
		case <-ticker.C:
			if !s.Paused {
				// Update game logic systems
				for _, sys := range s.systems {
					sys.Update(s.world)
				}
				time := s.tickRes.Get()
				time.Tick++
			}
		case <-uiTicker.C:
			// Update UI systems
			for _, sys := range s.uiSystems {
				sys.UpdateUI(s.world)
			}
			for _, sys := range s.uiSystems {
				sys.PostUpdateUI(s.world)
			}
		}
	}

	// Stop the tickers when done
	ticker.Stop()
	uiTicker.Stop()

	s.finalize()
}
```

**Comment by mlange-42** [comment]
@ImVexed Thanks for reporting!

Unfortunately, I was not able to get consistent frame rates/update rates for high intended rates using `Ticker`. May be due to the low time resolution on Windows systems, which is fixed by this code: https://github.com/mlange-42/arche-model/blob/main/model/time_windows.go

So for now, I fixed the issue by calculating the theoretical next update step even when paused (assuming 30 TPS to avoid fast looping when TPS is set to 0, i.e. unlimited): mlange-42/arche-model#47

Could you give that a try?

Also, feel free to make a PR with a solution using `Ticker` to check if the inconsistent frame rate issue persists.

**Comment by ImVexed** [comment]
Oh Interesting! I'm only running my systems at around 30/60TPS, so there's not a huge issue if things slip for me by a few ns. For me it's far more important to fit as many concurrent models on the same system as possible.

I'm also running on Linux as well, so not sure if the `time.Sleep` is any higher precision on there compared to windows. I tried the branch you linked but am still seeing 100% core usage when active and sleeping still. While using the ticker puts me around 0.1% usage while unpaused. I think something may be going wrong with the sleep calculations the way it's currently set up.   

My TPS is set to 30, and FPS 1 btw.

**Comment by mlange-42** [comment]
Could you give it a try again? The reason why you still had high CPU load was probably due to FPS beeing set to 30 when paused. Changed it to cap it to 30 only if it is above or unlimited (i.e. 0).

Regarding the ticker, I am also not sure how to handle the case of unlimited FPS/TPS then.

**Comment by ImVexed** [comment]
That's true, the ticker method probably wouldn't work with unlimited FPS/TPS. And regarding the CPU load. The high usage isn't coming from ticking at 30/s I'm doing very small amounts of work inside of the systems with only 10 or so entities. Mainly just ticking their position based on velocity. 

What I'm noticing is that `wait` is never > 0 for me.
```
	if wait > 0 {
		time.Sleep(wait)
	}
```

Even when running the system normally. It never sleeps and spins as quickly as possible

**Comment by ImVexed** [comment]
Also, in relation to this ticking: Do you think it would be possible to expose a delta time duration since last tick to systems? It would be quite useful for real time systems that may slip if things slow down.

**Comment by mlange-42** [comment]
> What I'm noticing is that wait is never > 0 for me.

That's weird. Even when using the branch? And you are sure both FPS and TPS are set above zero? When I print `wait` just before the condition, I get the expected 16ms for `TPS=60`, e.g.

> Also, in relation to this ticking: Do you think it would be possible to expose a delta time duration since last tick to systems? It would be quite useful for real time systems that may slip if things slow down.

This is quite easily achieved using a system to measure the delta, and a resource to store the value for access by other systems. So I am reluctant to hard-code it into the scheduler. See the `PerfTimer` system for an examples: https://github.com/mlange-42/arche-model/blob/main/system/perf_timer.go

**Comment by ImVexed** [comment]
Correct, on the branch I a break point on the sleep and it was never hit. Which would be a reasonable explanation for why I have a cpu core pinned at 100% when running system.On Oct 24, 2023 03:49, Martin Lange ***@***.***> wrote:

What I'm noticing is that wait is never > 0 for me.

That's weird. Even when using the branch? And you are sure both FPS and TPS are set above zero? When I print wait just before the condition, I get the expected 16ms for TPS=60, e.g.

Also, in relation to this ticking: Do you think it would be possible to expose a delta time duration since last tick to systems? It would be quite useful for real time systems that may slip if things slow down.

This is quite easily achieved using a system to measure the delta, and a resource to store the value for access by other systems. So I am reluctant to hard-code it into the scheduler. See the PerfTimer system for an examples: https://github.com/mlange-42/arche-model/blob/main/system/perf_timer.go

**Comment by mlange-42** [comment]
Could you please try and provide a minimal reproducing example, or at least you main file where you plug the model together?

**Comment by ImVexed** [comment]
Sure:
```
package main

import (
	"fmt"

	"github.com/mlange-42/arche-model/model"
	"github.com/mlange-42/arche/ecs"
)

func main() {
	m := model.New()
	m.TPS = 5

	m.AddSystem(&dummySystem{})

	m.Run()

}

type dummySystem struct{}

func (s *dummySystem) Initialize(w *ecs.World) {

}

func (s *dummySystem) Update(w *ecs.World) {
	fmt.Println("Update")

}

func (s *dummySystem) Finalize(w *ecs.World) {}
```

It's not necessarily and particular setup, just any time I run a system on ubuntu, I'm seeing 100% core utilization, and a breakpoint on `time.Sleep` in 
```
// Calculates and waits the time until the next update of UI update.
func (s *Systems) wait() {
	nextUpdate := s.nextUpdate

	if (s.Paused || s.FPS > 0) && s.nextDraw.Before(nextUpdate) {
		nextUpdate = s.nextDraw
	}

	t := time.Now()
	wait := nextUpdate.Sub(t)

	if wait > 0 {
		time.Sleep(wait)
	}
}
```
will never be hit.

**Comment by ImVexed** [comment]
That fixes it! Thanks!

**Comment by mlange-42** [comment]
@ImVexed Thanks again for reporting! The fix is available now in `arche-model` v0.4.1.
